name: 'app'
type: 'python:3.12'
relationships:
  rediscache: "cache:redis"
disk: 2048
web:
  commands:
    start: "poetry run uvicorn main:app --port $PORT --workers 1"
  locations:
    "/index":
      root: 'public'
      passthru: true
      index: [ "index.html" ]
      allow: true
    "/":
      root: 'public'
      passthru: true
      allow: true
    "/static":
      root: "static"
      expires: 1h
      allow: true

dependencies:
  python3:
    poetry: '*'

variables:
  env:
    POETRY_VIRTUALENVS_IN_PROJECT: true
    POETRY_VIRTUALENVS_CREATE: true

hooks:
  # The build hook is run after any build flavor.
  # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#build-hook
  build: |
    set -eu
    python3.12 -m pip install --upgrade uvicorn  
    poetry install
  deploy: |
    # Install dependencies
    # poetry lock --no-update
    # poetry install
    cp ./rag_interface/settings.yaml ./rag
    cp -r ./rag_interface/prompts ./rag
    # cp -r ./ragtest/output ./rag
    # cp -r ./rag_interface/input ./rag


source:
  ######################################################################################################################
  ##                                                                                                                  ##
  ## This source operation is part of the Platform.sh process of updating and maintaining our collection of           ##
  ## templates. For more information see https://docs.platform.sh/create-apps/source-operations.html and              ##
  ## https://github.com/platformsh/source-operations                                                                  ##
  ##                                                                                                                  ##
  ##                  YOU CAN SAFELY DELETE THIS COMMENT AND THE LINES BENEATH IT                                     ##
  ##                                                                                                                  ##
  ######################################################################################################################
  operations:
    auto-update:
      command: |
        curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0

mounts:
  '.cache':
    source: local
    source_path: cache
  'rag':
    source: local
  '.output':
    source: local
  '.config':
    source: tmp
  'outputs':
    source: local